name: PhantomRemover
version: '${project.version}'
main: me.serbob.phantomremover.PhantomRemover
api-version: 1.19
authors: [ Serbob ]
description: A plugin that enables/disables the spawn of phantoms.
commands:
  phantoms:
    description: Enables/disables the spawn of phantoms.
